github: [jbgoldco-ops]
custom: [
  "https://www.buymeacoffee.com/JbGoldspar8",
  "bitcoin:bc1qnp06qlcxeele8268dm9henwm00q9dwnk8f5f6t",
  "monero:44KXbQ47GskEsy12FVRKPEEaBpBeNWMJ4CoTU3No8tB96wrLyWBgz4hTVriiw1mtK3gF7Tazn3K3nJnufZrQPfiKHd1h5vj"
]
